%\VignetteIndexEntry{genomationData}
%\VignetteKeywords{genomationData}
%\VignettePackage{genomationData}

\documentclass[12pt]{article}

\usepackage{amsmath}
\usepackage{hyperref}
\usepackage[authoryear,round]{natbib}

\textwidth=6.2in
\textheight=8.5in
\oddsidemargin=.1in
\evensidemargin=.1in
\headheight=-.3in

\newcommand{\scscst}{\scriptscriptstyle}
\newcommand{\scst}{\scriptstyle}
\newcommand{\Rcode}[1]{{\texttt{#1}}}
\newcommand{\Rpackage}[1]{{\textit{#1}}}

\author{Altuna Akalin & Vedran Franke}

\title{\textsf{genomationData: R package with various types of genomic data}}

\date{October 25, 2013}

\begin{document}
<<setup, echo=FALSE>>=
options(width = 60)
olocale=Sys.setlocale(locale="C")
@ 
\maketitle

\tableofcontents

% ----------------------------------------------------------------- %
\section{Introduction}

\Rpackage{genomationData} is a Bioconductor-compliant R package that contains raw and processed data from high throughput genomics experiments. The data is originaly intended for demonstration of the Bioconductor package \Rpackage{genomation}.
\Rpackage{genomationData} holds data from CHiP Seq and Bisulphite sequencing experiments produced by Encode and Epigenetics Roadmap. All datasets come from human H1 embryonic stem cell line and are mapped to the hg19/GRCh37 version of the genome.


% ----------------------------------------------------------------- %
\section{Getting started}

To load the \Rpackage{genomationData} package into your R envirnoment type:
<<>>=
library(genomationData)
@

\subsection{Sample description}
To list the available files type:
<<>>=
list.files(system.data(package='genomationData'))
@

The package currently holds 5 CHiP Sequencing and one Bisulfite sequencing samples. 
Files with the .bam extension contain raw CHiP seq reads, while  *.broadPeak and *.narrowPeak represent processed peaks. Due to the large sizes of the samples, the *.bam files have been restricted to human chromosome 21 (chr21).
GSM429321_UCSD.H1.Bisulfite-Seq.combined.chr21.bedGraph.gz contains methylation calls for each CpG dinucleotide on human chromosome 21. The original file was converted from wig into bedGraph format using the standard UCSC applications.

To see complete information about the files, take a look into SamplesInfo.txt
<<>>=
samp.info = read.table(file.path(system.data(package='genomationData','SamplesInfo.txt'), header=T)
head(samp.info)
@

% ----------------------------------------------------------------- %
\section{Session Info}
<<>>=
sessionInfo()
@

\bibliographystyle{apalike}
\bibliography{genomationData}
\end{document}
